# Generated by Django 6.0.5 on 2026-05-17 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        ("messages_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=32)),
                (
                    "provider_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("recipient", models.CharField(blank=True, max_length=320)),
                (
                    "recipient_token",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("link_url", models.TextField(blank=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("bounce_reason", models.CharField(blank=True, max_length=500)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="connections.connection",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="messages_api.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["message", "occurred_at"],
                        name="events_even_message_4c0af9_idx",
                    ),
                    models.Index(
                        fields=["type", "occurred_at"],
                        name="events_even_type_a430ba_idx",
                    ),
                ],
            },
        ),
    ]
