# Generated by Django 6.0.5 on 2026-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_webhookendpoint_webhookdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="simulated",
            field=models.BooleanField(default=False),
        ),
    ]
