# Generated by Django 6.0.5 on 2026-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="latest_release_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="latest_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="update_check_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="update_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
