# Generated by Django 6.0.5 on 2026-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_workspacesettings_latest_release_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="ai_api_key_encrypted",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="ai_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Google Gemini"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="safe_browsing_api_key_encrypted",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="safe_browsing_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
