# Generated by Django 6.0.5 on 2026-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_workspacesettings_ai_api_key_encrypted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="retention_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
