# Generated by Django 6.0.5 on 2026-05-17 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "routing_strategy",
                    models.CharField(
                        choices=[
                            ("weighted", "Weighted"),
                            ("failover", "Failover"),
                            ("round_robin", "Round-robin"),
                        ],
                        default="weighted",
                        max_length=24,
                    ),
                ),
                ("health_skip_enabled", models.BooleanField(default=True)),
                ("recent_5xx_threshold", models.PositiveIntegerField(default=5)),
                (
                    "recent_bounce_rate_threshold_pct",
                    models.PositiveIntegerField(default=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
