# Generated by Django 6.0.5 on 2026-05-17 16:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
        ("pools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="rr_cursor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WarmupPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curve",
                    models.CharField(
                        choices=[
                            ("sendgrid-standard", "SendGrid standard (30 days)"),
                            ("aggressive", "Aggressive (14 days)"),
                            ("custom", "Custom"),
                        ],
                        default="sendgrid-standard",
                        max_length=32,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                (
                    "daily_caps_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom curve caps. Ignored for preset curves.",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warmup_plan",
                        to="pools.pool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoolMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Used by the weighted strategy. 0 disables the member.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower = preferred for failover. Members at the same priority tier round-robin.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("daily_sent_count", models.PositiveIntegerField(default=0)),
                ("daily_counter_date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships",
                        to="connections.connection",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="pools.pool",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pool", "connection"), name="uniq_pool_connection"
                    )
                ],
            },
        ),
    ]
