# Generated by Django 6.0.5 on 2026-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pools", "0002_pool_rr_cursor_warmupplan_poolmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="mode",
            field=models.CharField(
                choices=[
                    ("live", "Live — route to upstream providers"),
                    ("capture", "Capture — store in the Test Inbox, never send"),
                ],
                default="live",
                max_length=12,
            ),
        ),
    ]
