"""Unified Event model — every webhook from every provider lands here in a
single normalized shape. Plus WebhookEndpoint for outbound delivery."""
from __future__ import annotations

import secrets

from django.db import models
from django.utils import timezone


class Event(models.Model):
    # Mirrors NormalizedEvent.EVENT_TYPES — kept as a plain CharField so future
    # provider additions don't require migrations.
    message = models.ForeignKey(
        "messages_api.Message",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="events",
    )
    connection = models.ForeignKey(
        "connections.Connection",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="events",
    )

    type = models.CharField(max_length=32, db_index=True)
    provider_event_id = models.CharField(max_length=255, unique=True, db_index=True)
    provider_message_id = models.CharField(max_length=255, blank=True, db_index=True)
    recipient = models.CharField(max_length=320, blank=True)
    recipient_token = models.CharField(max_length=120, blank=True, db_index=True)
    occurred_at = models.DateTimeField(db_index=True)

    link_url = models.TextField(blank=True)
    user_agent = models.CharField(max_length=500, blank=True)
    ip = models.GenericIPAddressField(null=True, blank=True)
    bounce_reason = models.CharField(max_length=500, blank=True)

    raw = models.JSONField(default=dict, blank=True)
    # True for events generated by the Test Inbox simulator (sandbox messages)
    # rather than received from a real provider webhook. Surfaced to outbound
    # endpoints so receivers can distinguish test traffic (cf. Stripe livemode).
    simulated = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ("-occurred_at", "-created_at")
        indexes = [
            models.Index(fields=["message", "occurred_at"]),
            models.Index(fields=["type", "occurred_at"]),
        ]

    def __str__(self) -> str:
        return f"Event<{self.type} {self.provider_event_id[:20]}>"


def _gen_signing_secret() -> str:
    return "whsec_" + secrets.token_urlsafe(32)


class WebhookEndpoint(models.Model):
    """An outbound webhook target — the customer's app receives these.

    `event_types` is a list of normalized event types (see NormalizedEvent.EVENT_TYPES).
    Empty list means "all events".
    """

    name = models.CharField(max_length=120)
    url = models.URLField()
    signing_secret = models.CharField(max_length=64, default=_gen_signing_secret)
    enabled = models.BooleanField(default=True)
    event_types = models.JSONField(default=list, blank=True)

    last_attempted_at = models.DateTimeField(null=True, blank=True)
    last_succeeded_at = models.DateTimeField(null=True, blank=True)
    consecutive_failures = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name

    def wants(self, event_type: str) -> bool:
        if not self.enabled:
            return False
        if not self.event_types:
            return True
        return event_type in self.event_types


class WebhookDelivery(models.Model):
    """One delivery attempt for an outbound webhook — used for retry bookkeeping."""

    STATUS_PENDING = "pending"
    STATUS_DELIVERED = "delivered"
    STATUS_FAILED = "failed"

    endpoint = models.ForeignKey(WebhookEndpoint, related_name="deliveries", on_delete=models.CASCADE)
    event = models.ForeignKey(Event, related_name="deliveries", on_delete=models.CASCADE)
    status = models.CharField(max_length=16, default=STATUS_PENDING)
    attempts = models.PositiveIntegerField(default=0)
    last_status_code = models.PositiveIntegerField(null=True, blank=True)
    last_error = models.CharField(max_length=500, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    delivered_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(fields=["endpoint", "event"], name="uniq_endpoint_event"),
        ]
