# Generated by Django 6.0.5 on 2026-05-17 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "provider_code",
                    models.CharField(
                        choices=[("resend", "Resend"), ("postal", "Postal")],
                        max_length=32,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Postal: required (e.g. https://postal.example.com). Resend: optional override.",
                    ),
                ),
                ("credentials_encrypted", models.BinaryField(blank=True, default=b"")),
                (
                    "webhook_secret_encrypted",
                    models.BinaryField(blank=True, default=b""),
                ),
                ("webhook_public_key_pem", models.TextField(blank=True)),
                (
                    "daily_cap",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional. 0 = unlimited."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_message", models.CharField(blank=True, max_length=255)),
                ("recent_5xx_count", models.PositiveIntegerField(default=0)),
                ("recent_total", models.PositiveIntegerField(default=0)),
                ("skip_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
