# Generated by Django 6.0.5 on 2026-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="recent_window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
