# Generated by Django 6.0.5 on 2026-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_connection_recent_window_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="aws_region",
            field=models.CharField(
                blank=True, help_text="SES: AWS region, e.g. us-east-1.", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="ses_configuration_set",
            field=models.CharField(
                blank=True,
                help_text="SES: configuration set name; required for SES to publish open/click/delivery events to SNS.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Postal: required (e.g. https://postal.example.com). Resend: optional override. SES: ignored (endpoint derived from region).",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="provider_code",
            field=models.CharField(
                choices=[
                    ("resend", "Resend"),
                    ("postal", "Postal"),
                    ("ses", "Amazon SES"),
                ],
                max_length=32,
            ),
        ),
    ]
