# Generated by Django 6.0.5 on 2026-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0003_connection_aws_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="sns_topic_arn",
            field=models.CharField(
                blank=True,
                help_text="SES: SNS topic ARN allowed to deliver events. Leave blank to lock onto the first topic that confirms a subscription.",
                max_length=255,
            ),
        ),
    ]
