# Generated by Django 6.0.5 on 2026-05-17 16:06

import apps.messages_api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("connections", "0001_initial"),
        ("pools", "0002_pool_rr_cursor_warmupplan_poolmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.messages_api.models._new_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_address", models.CharField(max_length=255)),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                ("bcc", models.JSONField(blank=True, default=list)),
                ("reply_to", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("body_encrypted", models.BinaryField(blank=True, default=b"")),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("recipient_tokens", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "idempotency_fingerprint",
                    models.CharField(blank=True, max_length=64),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("attempts", models.JSONField(blank=True, default=list)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retention_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="connections.connection",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="pools.pool",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="messages_api.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("content_id", models.CharField(blank=True, max_length=120)),
                ("content_b64", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messages_api.message",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["api_key", "idempotency_key"], name="msg_idem_key_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["expires_at"], name="messages_ap_expires_fb92b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("api_key", "key"), name="uniq_apikey_idem"
            ),
        ),
    ]
