# Generated by Django 6.0.5 on 2026-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sandbox",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                    ("captured", "Captured"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
    ]
