# Generated by Django 6.0.5 on 2026-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_api", "0002_message_sandbox_alter_message_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="spam_analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="spam_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="spam_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="spam_verdict",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
