# Generated by Django 6.0.5 on 2026-07-11 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_api", "0003_message_spam_analyzed_at_message_spam_report_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body_purged_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="PurgeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("manual", "Manual")],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("cutoff", models.DateTimeField(blank=True, null=True)),
                ("messages_purged", models.PositiveIntegerField(default=0)),
                ("attachments_purged", models.PositiveIntegerField(default=0)),
                ("idempotency_purged", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
    ]
